name: flutter_trip
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.4
  http: ^0.12.0+1
  flutter_webview_plugin: ^0.3.5
  flutter_staggered_grid_view: ^0.3.0
  underline_indicator: ^0.0.2
  flutter_splash_screen: ^0.1.0

flutter:

  uses-material-design: true

